/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EvilevilevilRouteImport } from './routes/evilevilevil'
import { Route as IndexRouteImport } from './routes/index'

const EvilevilevilRoute = EvilevilevilRouteImport.update({
  id: '/evilevilevil',
  path: '/evilevilevil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evilevilevil': typeof EvilevilevilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evilevilevil': typeof EvilevilevilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evilevilevil': typeof EvilevilevilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evilevilevil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evilevilevil'
  id: '__root__' | '/' | '/evilevilevil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvilevilevilRoute: typeof EvilevilevilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/evilevilevil': {
      id: '/evilevilevil'
      path: '/evilevilevil'
      fullPath: '/evilevilevil'
      preLoaderRoute: typeof EvilevilevilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvilevilevilRoute: EvilevilevilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
